### ISSUE TITLE
3 Issues with Livemessage

### ISSUE THREAD

**Issue by ttorynn** [rebane2001/livemessage#11]
Don't get me wrong, I LOVE THIS MOD it's GREAT. But, there are a few problems with it and here they are:

1. Low UI FPS.
When i use the UI it is choppy when moving stuff, it doesn't affect the usability of it but is just slightly annoying. I can get a video of it if needed.
2. Cant hold backspace
This one is really annoying for me, when typing messages, i can't mass delete by holding the backspace button which is really annoying if the subject changes or something.
3. No "Insertion point" when typing a message
When i first used this i was confused if i was typing in the message box or not because there was no blinking line where i was typing, this one is really nitpicky and is not needed just a quality of life feature.

That's it, other than those this is great and functions well!

**Comment by rebane2001** [comment]
1. The UI FPS is great, I think you are mistaking it for input delay, as at the moment it only takes input every time Minecraft gives it (every tick).
2. This fix is already implemented, but is not in the latest build.
3. I might consider adding it, it will require a bit of effort as Minecraft's blinking cursor uses a weird system.

**Comment by rebane2001** [comment]
Adding to 1, I do plan on implementing a fix to get better input delay from the mouse.

**Comment by ttorynn** [comment]
Alright thanks, i would tag this as "enhancement"

**Comment by rebane2001** [comment]
Added in 1bb83b210694744a88295c433b69401ce0e33996 and 228a34e06cca9bfdea2dfa8d9977d01b7487f56a
