### ISSUE TITLE
Activating chat modifications on another utility client makes livemessage not show/save messages

### ISSUE THREAD

**Issue by Remi4896** [rebane2001/livemessage#2]
activating chat modifications on another utility client makes livemessage not show/save messages

If you turn the chat modification module on (even if you dont activate any of these modifications) will make it not work properly. You still can send messages with the mod but they wont show in the gui.

**Comment by rebane2001** [comment]
Could you please specify which utility client you're using?

**Comment by lifetorrent** [comment]
I personally use Rusher and am having this issue. Increasing the chat history size seems to work just fine but once I enable "Timestamps" I get the issue described above.

**Comment by rebane2001** [comment]
Okay, that makes a lot more sense! I'll soon implement some features to prevent timestamps from messing up the chat.

**Comment by rebane2001** [comment]
Fixed in 32ed688414c520f9c0dc599ef8ebe3691c8f49b1, let me know if you still have any issues
