### ISSUE TITLE
Rusherhack doesnt respect typing...

### ISSUE THREAD

**Issue by ttorynn** [rebane2001/livemessage#22]
My default rhack kebind is Right Shift, but when i try to capitalize a letter in livemessage or do a special character it opens the gui instead of letting me type. Kami blue doesnt do this only rusherhack. Im wondering if you can fix it.

**Comment by rebane2001** [comment]
This is an issue that can only be fixed in Rusherhack itself. I've contacted John about it and he said he'd fix it, so just wait for an update I guess.

**Comment by ttorynn** [comment]
Alright
