### ISSUE TITLE
'Normal behaviour' file management is spammy in logs

### ISSUE THREAD

**Issue by Entropy5** [rebane2001/livemessage#6]
![2021-02-02 19_05_20](https://user-images.githubusercontent.com/44469915/106643444-093fcb00-658a-11eb-8a8d-3c5454fdda9f.png)

**Comment by rebane2001** [comment]
This is confirmed and planned to be fixed in the next version

**Comment by rebane2001** [comment]
Fixed in 4ff5e045e417e189404630309855152a9788eb91
